spring:
  application:
    name: Backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.194.182:3306/movie_db?useSSL=false&serverTimezone=UTC
    username: movie
    password: Movie123456

server:
  port: 8080   # 修改当前后端程序运行在的端口号

jwt:
  secret: 3d96e190c624be5cb7f0fb062d3e6b5a225f596bede38530d1de1d997fbc0c6d
  expiration: 86400000