@startuml
' 设置皮肤参数
skinparam monochrome true
skinparam class {
    BackgroundColor #EEEEFF
    BorderColor #6666AA
    ArrowColor #6666AA
}

class Comment {
    -user_id: int (PK)
    -movie_id: int (PK)
    -comment: text
    -time: timestamp
}
@enduml