@startuml
' 设置皮肤参数
skinparam monochrome true
skinparam class {
    BackgroundColor #EEEEFF
    BorderColor #6666AA
    ArrowColor #6666AA
}

' 定义User类图
class User {
    -id: int (PK)
    -name: varchar(255)
    -password: varchar(255)
}
@enduml